(load "utilities.el")
(defun joc-total-recomputation ()
  (let ((directories  '("../finalResultsSC" "../finalResultsSPL")))
    (dolist (directory directories)
      (let* ((default-directory directory)
	   ( runs  (directory-files nil "run*")))
	(dolist (run runs)
	  (let  ((default-directory
		   (concat (file-name-as-directory run) "output")))
	    (dolist (solver-file (directory-files nil "solver*"))
	      (joc-trajectories-time solver-file))
	    (dolist (solver-file (directory-files nil "watcher*"))
	      (joc-trajectories-memory solver-file)))
	  )))
)
  )
