(load-file "utilities.el")
(let ((default-directory default-directory))
(directory-files "../finalResultsSC")
)

(defun joc-total-recomputation ()
  (let ((default-directory default-directory)
	(directories '("../finalResultsSC/" "../finalResultsSPL/")))
    (dolist (directory directories)
      (let* ((default-directory (concat default-directory directory))
	     runs)
	(setq runs (directory-files "." nil "run*"))
	(dolist (run runs)
	  (let  ((default-directory
		   (concat default-directory (file-name-as-directory run) "output/")))
	    (dolist (solver-file (directory-files "." nil "^solver*"))
	      (joc-trajectories-time solver-file))
	    (dolist (watcher-file (directory-files "." nil "^watcher*"))
	      (joc-trajectories-memory watcher-file)))
	  )))))
