(defun joc-trajectrories-time (&optional file)
  (interactive "P")
  (if file   (set-buffer (create-file-buffer file)))
  (goto-char (point-min))
  ;; (occur "[0-9]*\.[0-9]*/[0-9]*\.[0-9]*[[:blank:]]o")
  (goto-char (point-min))
  (forward-line)
  (setq n 0)
  (kill-region 1 1)
  (setq result "")
  (let (start)
    (while  (search-forward-regexp   "[0-9]*\\.[0-9]*/[0-9]*\\.[0-9]*[[:blank:]]o" (point-max) t )
      (move-beginning-of-line)
      (search-forward  "/")
      (setq start (point))
      (search-forward-regexp  "[0-9]\\w")
      (copy-to-register start (point))
      (insert  ", ")
      (incf n)
      ))
  (unless (= n 0)
    (search-backward ",")
    (kill-line))
  )
